[package]
name = "attempt-linker"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-maybe-link = {path = "../lib-maybe-link", features = ["linker-script"]}
